import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import styles from "../styles/Home.module.css";
import ExampleUI from "./views/ExampleUI.jsx";

const Home: NextPage = () => {
  const { address } = useAccount();
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <ExampleUI address={address} />
      </main>

      <footer className={styles.footer} style={{ color: "white" }}>
        <a
          href="https://all-weather.webflow.io/"
          rel="noopener noreferrer"
          target="_blank"
        >
          All Weather Protocol
        </a>
      </footer>
    </div>
  );
};

export default Home;
