import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import styles from "../styles/Home.module.css";
import ExampleUI from "./views/ExampleUI.jsx";

const Home: NextPage = () => {
  // TODO(david): use the account address to fetch the user's data, once I've deployed the contract
  // const { address } = useAccount();
  const address =
    "0xe4bac3e44e8080e1491c11119197d33e396ea82b+0x7ee54ab0f204bb3a83df90fdd824d8b4abe93222+0x43cd745bd5fbfc8cfd79ebc855f949abc79a1e0c+0x038919c63aff9c932c77a0c9c9d98eabc1a4dd08";
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <ExampleUI address={address} />
      </main>

      <footer className={styles.footer} style={{ color: "white" }}>
        <a
          href="https://all-weather.webflow.io/"
          rel="noopener noreferrer"
          target="_blank"
        >
          All Weather Protocol
        </a>
      </footer>
    </div>
  );
};

export default Home;
